version: '3.6'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    ports:
      - 3000:3000
    links:
      - server
    tty: true
    command: yarn start

  server:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    volumes:
      - ./server:/home/gradle/server
      - ./server/data/processed:/root/memegle/images
    environment:
      - MONGO_URI=mongodb://mongo1:27017/memegle?replicaSet=rs0
      - ES_URI=es:9200
    ports:
      - 8080:8080
    depends_on:
      - monstache
    links:
      - mongo1
      - es
    command: ["sh", "./scripts/init-dev.sh"]

  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:4.0-xenial
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    volumes:
      - rs1:/data/db
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

  init-mongo-rs:
    image: mongo:4.0-xenial
    links:
      - mongo1
    depends_on:
      - mongo1
    volumes:
      - ./scripts:/scripts
    entrypoint: ["sh", "/scripts/mongo_init.sh"]

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.7
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: always


  # https://rwynn.github.io/monstache-site/start/
  monstache:
    image: rwynn/monstache:rel5
    container_name: monstache
    working_dir: /app
    command: -f ./monstache.config.toml
    volumes:
      - ./monstache.config.toml:/app/monstache.config.toml
    depends_on:
      - init-mongo-rs
      - es
    ports:
      - 8081:8080     # host-port:container-port
    links:
      - mongo1:mongo1
      - es:es
    restart: always

volumes:
  rs1:
  esdata:
    driver: local
  gradle-cache: