# https://rwynn.github.io/monstache-site/start/
direct-read-namespaces = ["memegle.pictures"]

gzip = true
stats = true
index-stats = true

namespace-regex = '^memegle\.pictures$'
elasticsearch-max-conns = 4
dropped-collections = true
dropped-databases = true
replay = false
resume = true
verbose = false

exit-after-direct-reads = false
