version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo1:27017/memegle?replicaSet=rs0
      - ES_URI=es:9200
      - MEMEGLE_APP_PRODUCTION_MODE=${MEMEGLE_APP_PRODUCTION_MODE}
    ports:
      - 8080:8080
    depends_on:
      - mongo1
      - es
      - monstache
    links:
      - mongo1
      - es

  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:4.0-xenial
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    volumes:
      - rs1:/data/db
      #- ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

  mongo-setup:
    image: mongo:4.0-xenial
    links:
      - mongo1:mongo1
    depends_on:
      - mongo1
    volumes:
      - ./scripts/sh:/scripts
    entrypoint: ["sh", "/scripts/mongo_init.sh"]

# https://www.docker.elastic.co/r/elasticsearch
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.7
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: always

  # https://rwynn.github.io/monstache-site/start/
  monstache:
    image: rwynn/monstache:rel5
    container_name: monstache
    working_dir: /app
    command: -f ./monstache.config.toml
    volumes:
      - ./monstache.config.toml:/app/monstache.config.toml
    depends_on:
      - mongo-setup
      - es
    ports:
      - 8081:8080
    links:
      - mongo1:mongo1
      - es:es
    restart: always


volumes:
  rs1:
  esdata:
    driver: local
