version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017/
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db

  db:
    container_name: mongodb
    image: mongo:4.2.5
#    environment:
#      - MONGO_INITDB_DATABASE=memegle
#      - MONGO_INITDB_ROOT_USERNAME=memegle
#      - MONGO_INITDB_ROOT_PASSWORD=memegle
    volumes:
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata: